# Site settings
title: A Place to Remember
author: Boy Sandy Gladies Arriezona
header-img: img/home-bg.jpg
email: reno.esper@gmail.com
copyright_name: A Place to Remember
description: "Thoughts, stories and ideas."
baseurl: ""
url: "https://renodesper.com"
twitter_username: renodesper
github_username: renodesper
facebook_username: renodesper
email_username: reno.esper@gmail.com

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
